name: rospatent
description: Hackathon Rospatent SFedU
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.9
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  dio: ^4.0.6
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
